name: spatialist_test
favicon: null
layout_spectrum: 0.8786685112863779
typography_spectrum: 0.8897555957082659
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7426480837166309
  lightness: 0.6049868520349264
  saturation: 0.015175314620137215
  rhythmicContrast: 0.3196002955082804
purpose: []
